extern crate safe_transmute;

mod guarded_transmute;
mod guarded_transmute_many;
mod guarded_transmute_pedantic;
mod guarded_transmute_many_pedantic;
mod guarded_transmute_many_permissive;
mod guarded_transmute_vec;
mod guarded_transmute_vec_pedantic;
mod guarded_transmute_vec_permissive;
