(function() {var implementors = {};
implementors["safe_transmute"] = [{text:"impl&lt;S:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a>, T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"enum\" href=\"safe_transmute/error/enum.Error.html\" title=\"enum safe_transmute::error::Error\">Error</a>&lt;S, T&gt;",synthetic:false,types:["safe_transmute::error::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"safe_transmute/error/struct.GuardError.html\" title=\"struct safe_transmute::error::GuardError\">GuardError</a>",synthetic:false,types:["safe_transmute::error::GuardError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"enum\" href=\"safe_transmute/error/enum.ErrorReason.html\" title=\"enum safe_transmute::error::ErrorReason\">ErrorReason</a>",synthetic:false,types:["safe_transmute::error::ErrorReason"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"safe_transmute/error/struct.UnalignedError.html\" title=\"struct safe_transmute::error::UnalignedError\">UnalignedError</a>",synthetic:false,types:["safe_transmute::error::UnalignedError"]},{text:"impl&lt;S:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a>, T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"safe_transmute/error/struct.IncompatibleVecTargetError.html\" title=\"struct safe_transmute::error::IncompatibleVecTargetError\">IncompatibleVecTargetError</a>&lt;S, T&gt;",synthetic:false,types:["safe_transmute::error::IncompatibleVecTargetError"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
